dist: trusty
sudo: required
language: go
go: "1.10"
addons:
  postgresql: "11.2"
before_script:
  - psql -U postgres -c "ALTER SYSTEM SET wal_level TO 'logical';"
  - psql -U postgres -c "ALTER SYSTEM SET max_replication_slots TO '10';"
  - sudo /etc/init.d/postgresql restart 
services:
  - docker
  - postgresql
install: make setup
script: make ci
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
